### PR TITLE
Add missing dependency added in #132

### PR DESCRIPTION
**Pull request by T0RAT0RA**
Sorry I forgot to add `react-router-dom` in #132  

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by jvilimek** [comment]
No worries. The `lint` step should have failed in the previous PR during CI phase.. but maybe the sources were not synchronized, this is something I have added just recently ([#126](https://github.com/Oriflame/backstage-plugins/pull/126))

**Comment by T0RAT0RA** [comment]
It's still failing but I don't know why. I tried a bunch of different updates on the `yarn.lock` and `package.json` files, but I don't know what's going on.

**Comment by jvilimek** [comment]
I believe the `"react-router-dom": "6.4.3"` needs to be added to devDependencies to the plugin as it is now used in tests

**Comment by jvilimek** [comment]
I have updated my comments. Shall I fix it? I can have PR up and running in no time.

**Comment by T0RAT0RA** [comment]
> Shall I fix it? 

Yes please, thanks!
there is something wrong with my setup, the linter doesn't pick up the issue. I'l have to investigate later.

**Comment by jvilimek** [comment]
sure, np. Created #145 . Closing this one.

**Pull request closed without merging**
