### PR TITLE
Add ability to override Entity scorecard path

### PR DESCRIPTION
**Pull request by T0RAT0RA**
I'd like to have the scorecard json files in the Github repositories, along with the component code.
We could have an annotation to override the URL to fetch the data from:

```diff
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-system-1
  description: |
    A sample system
+  annotations:
+    score-card/url: /url/to/score/card.json
``` 

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [ ] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

### CODE REVIEW

**Comment by jvilimek** [comment]
Thanks a lot for the suggestion.
I understand you want to have data for scoring near the code base. So this ` /url/to/score/card.json` is relative to the (git) repository where the component is? Because of how you have implemented it (I know, it's a draft), it seems it's downloaded from an absolute path on the Backstage front-end. Maybe we can join the path with the current location of the source code (or the location of the backstage YAML definition)?

There is another question that tickles my mind. What shall we do with the aggregation data (i.e. `all.json`) used for the dashboard? Maybe some job, that will check all entities for their scoring data aggregating them in the DB? Like from the `scorecards.jsonDataUrl` + all custom scoring data in entities?

**Comment by T0RAT0RA** [comment]
I used a relative URL in my example because I'll still need a backend proxy to retrieve the file from a private repository, which the frontend won't be able to do.

I know the `all.json` is a problem, and my backend proxy would take care of that in theory.
Ideally, my CI pipeline pushes the scorecards from the repository into a central place in backstage, a backend plugin or s3 bucket.
I need to think it more thoroughly though.


The thing is I wanted the frontend to also give the entity reference to the backend, to know the type of the entity, because I'm using it to score components and not system. So I'd like my backend proxy to know which entity it is, to retrieve the annotation and find where the scorecard is located, if that makes sense

**Comment by jvilimek** [comment]
Ok I understand. Would it help to add entity `namespace`, and `kind` to the path in [ScoringDataJsonClient](https://github.com/Oriflame/backstage-plugins/blob/6a67e1c30c8c856bbfd1fbffeb8aee90b6a2c00e/plugins/score-card/src/api/ScoringDataJsonClient.ts#L58) 
```
  const urlWithData = `${jsonDataUrl}${entityNamespace}/${entityKind}/${entityName}.json`;
```
? In case the `scorecards.jsonDataUrl` config may target the backend proxy/api.

In the end, it's up to you to implement your own client to retrieve the data. And you can use whatever new annotation you would introduce.

Anyway, there is another feature suggestion [Component Level View with Overall System Score](#99) that we might consider. I.e. to have more freedom in what kind of entity you want to score.

WDYT?

**Comment by T0RAT0RA** [comment]
Yes, adding the `namespace` and `kind` to the URL path would be the best!
I was about to reply in https://github.com/Oriflame/backstage-plugins/issues/99 actually, with current implementation I can already score any entities, and add the `EntityScoreCardContent` component to its page.
```diff
+    <EntityLayout.Route path="/score" title="Score">
+      <Grid container spacing={3} alignItems="stretch">
+        <Grid item xs={12}>
+          <EntityScoreCardContent />
+        </Grid>
+      </Grid>
+    </EntityLayout.Route>
```


But having the `namespace` and `kind` will help building a better proxy, as I'll now which type it is on the backend, and won't have to make assumptions.

**Pull request closed without merging**
